version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "9001:9001"
    networks:
      - app_network

  client:
    build: ./client
    depends_on:
      - server
    networks:
      - app_network
    stdin_open: true
    tty: true

networks:
  app_network:
    driver: bridge
